# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DFS_recursive_R <- function(tails_R, heads_R, node) {
    .Call(`_WeimingSCC_DFS_recursive_R`, tails_R, heads_R, node)
}

SCC_solution_1 <- function(tails_R, heads_R, verbose = FALSE) {
    .Call(`_WeimingSCC_SCC_solution_1`, tails_R, heads_R, verbose)
}

SCC_solution_2 <- function(tails_R, heads_R, verbose = FALSE) {
    .Call(`_WeimingSCC_SCC_solution_2`, tails_R, heads_R, verbose)
}

generate_adjacency_list_R <- function(tails_R, heads_R) {
    .Call(`_WeimingSCC_generate_adjacency_list_R`, tails_R, heads_R)
}

DFS_nonrecursive_R <- function(tails_R, heads_R, node) {
    .Call(`_WeimingSCC_DFS_nonrecursive_R`, tails_R, heads_R, node)
}

SCC_solution_3 <- function(tails_R, heads_R, verbose = FALSE) {
    .Call(`_WeimingSCC_SCC_solution_3`, tails_R, heads_R, verbose)
}

